---
apiVersion: v1
kind: Service
metadata:
  # should be same name (ingress serviceName Part)
  name: wp-clusterip
  labels:
    # To connect with pod 
    app: wp
spec:
  selector:
    # To connect with pod 
    app: wp
  ports:
  # open the http and https port(80, 443) because we use the tls
  - name: http
    port: 80
  - name: https
    port: 443