---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-deployment
spec:
  # Replica
  replicas: 2
  selector:
    matchLabels:
      # should be same label with svc
      app: wp
      # To use Affinity
      tier: wordpress
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  minReadySeconds: 30
  template:
    metadata:
      name: wordpress
      labels:
        app: wp
        tier: wordpress
    spec:
      #affinity 
      affinity:
        # pod anti affinity
        # If has tier: wordpress, they are placed on different nodes.
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchExpressions:
                - key: tier
                  operator: In
                  values:
                  - wordpress
        # pod affinity
        # To be close with db pod 
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: tier
                operator: In
                values:
                  - db
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: wordpress
          image: wordpress:latest
          # Environment variable
          env:
            - name: WORDPRESS_DB_HOST
              value: "mysql-0.mysql"
            - name: WORDPRESS_DB_USER
              value: "wp-admin"
            - name: WORDPRESS_DB_PASSWORD
              value: "1234"
            - name: WORDPRESS_DB_NAME
              value: "wordpress"
          ports:
            - containerPort: 80
          # liveness Probe
          # http Get Probe
          livenessProbe:
            httpGet:
              port: 80
              path: /
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          # readiness Probe
          # Check the /var/www/html
          readinessProbe:
            exec:
              command: 
              - ls 
              - /var/www/html/
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 1  
          resources:
            requests:
              cpu: 500m
              memory: 200Mi
            limits:
              cpu: 1000m
              memory: 800Mi
          volumeMounts:
            - name: wp-vol
              mountPath: /var/www/html
      # Use the ceph storage
      volumes:
        - name: wp-vol
          persistentVolumeClaim:
            claimName: wp-pvc